language: node_js
node_js:
 - "node"

install:
- npm install newman

before_script:
- node --version
- npm --version
- newman --version

script:
- newman run test/API_Automation.postman_collection.json -g test/My_Workspace.postman_globals.json
